"""Cross-implementation parity against ebics-client-php golden vectors.

The fixtures under fixtures/parity/ are real requests captured from ebics-client-php
(a production EBICS client), regenerated by tools/php-parity/generate.php. These tests
prove our canonicalisation, digest, and signature verification agree with an independent
implementation over EBICS-shaped input — the check our own round-trip tests cannot give.

Scope note: the INI/HIA order-data *structure* is deliberately not asserted here. EBICS
3.0 (H005) transmits public keys as X.509 certificates (ds:X509Data), and these fixtures
were generated without a certificate generator, so their order data is incomplete. The
signed HPB request — which exercises the failure-prone AuthSignature — is fully valid and
is what these tests lock down.
"""

import base64
import json
from pathlib import Path

import pytest
from cryptography.hazmat.primitives.serialization import load_pem_public_key
from lxml import etree

from ebicsclient import crypto

_FIXTURES = Path(__file__).parent / "fixtures" / "parity"
_DS = "http://www.w3.org/2000/09/xmldsig#"


def _meta() -> dict:
    return json.loads((_FIXTURES / "meta.json").read_text())


def _hpb_root() -> etree._Element:
    return etree.fromstring((_FIXTURES / "hpb.xml").read_bytes())


def test_fixtures_present() -> None:
    # Guard: without the committed fixtures these parity tests would silently pass.
    for name in ("hpb.xml", "ini.xml", "hia.xml", "meta.json"):
        assert (_FIXTURES / name).is_file(), f"missing parity fixture {name}"


def test_reference_hpb_declares_inclusive_canonicalization() -> None:
    # The reference client uses inclusive Canonical XML 1.0 — the EBICS-mandated algorithm.
    root = _hpb_root()
    for tag in ("CanonicalizationMethod", "Transform"):
        element = root.find(f".//{{{_DS}}}{tag}")
        assert element is not None
        assert element.get("Algorithm") == "http://www.w3.org/TR/2001/REC-xml-c14n-20010315"


def test_our_digest_matches_reference_digest_value() -> None:
    # Our canonicalisation + SHA-256 over the authenticated nodes must reproduce the
    # DigestValue the reference client computed.
    root = _hpb_root()
    our_digest = base64.b64encode(crypto.digest_authenticated_nodes(root)).decode("ascii")
    assert our_digest == root.findtext(f".//{{{_DS}}}DigestValue")


def test_our_verifier_accepts_reference_signature() -> None:
    # Our AuthSignature verification must accept a signature produced by the reference
    # client (checks digest, SignedInfo canonicalisation, and rsa-sha256 together).
    public_key = load_pem_public_key(_meta()["keys"]["authentication"]["public"].encode("ascii"))
    assert crypto.verify_auth_signature(_hpb_root(), public_key)


def test_our_verifier_rejects_a_tampered_reference_request() -> None:
    root = _hpb_root()
    host_id = root.find(".//{urn:org:ebics:H005}HostID")
    assert host_id is not None
    host_id.text = "TAMPERED"
    public_key = load_pem_public_key(_meta()["keys"]["authentication"]["public"].encode("ascii"))
    assert not crypto.verify_auth_signature(root, public_key)


@pytest.mark.parametrize("order", ["ini", "hia", "hpb"])
def test_reference_requests_use_admin_order_type(order: str) -> None:
    root = etree.fromstring((_FIXTURES / f"{order}.xml").read_bytes())
    assert root.findtext(".//{urn:org:ebics:H005}AdminOrderType") == order.upper()
